# Site settings
head_title: Rob Bikmansurov | CIO, Ruby on Rails Developer
email:       robb@mail.ru
author:      Rob Bikmansurov
description: Rob Bikmansurov - CIO in the local universal bank, Full Stack web development, specializing in Ruby on Rails. Project manager. Software architect.
keywords: Ruby on Rails, Ruby, remote developer, performance, business-process optimization
baseurl:     ""
url:         "" # https://pawelurbanek.com"
date_format: "%b %-d, %Y"
structured_date_format: '%Y-%m-%d'
grammarly_link: https://grammarly.com
# digital_ocean_link: https://www.digitalocean.com/
# abot_link: https://abot.app
# email_subscription_link: https://mailchimp.com/
header_pages:
 - pages/home.html
 - pages/about.md
 - pages/piggy-bank.md
 - pages/cv.md

# Google services
google_verification: UA-116685631-1
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_tag_manager: GTM-5R726R5

# Optional features
animated:             false
show_post_footers:    true
show_social_icons:    true
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: robbikmansurov

# Social icons
github_username: robbikmansurov
twitter_username: /robbikmansurov
linkedin_username: robbikmansurov
medium_id:
flattr_button:
github: robbikmansurov
gitlab: robbikmansurov

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_twitter: true
share_facebook: true

text:
  pagination:
    newer: 'here'
    older: 'there'
  share_buttons:
    text:         'Share:'
    twitter:      'Share on Twitter'
    facebook:     'Share on Facebook'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    ''
    content:  ''
    subject:  'New submission!'
    submit:   'Send'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:title
paginate:     7
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - deploy.sh
  - certificates.tar
  - app-nginx.conf.sigil
  - purge.rb
  - CHECKS
  - app.json
  - .env

defaults:
  - scope:
      path: 'files/*.pdf'
    values:
      sitemap: false
  - scope:
      path: 'build/'
    values:
      sitemap: false
assets:
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  digest: true
  sources:
    - _assets/css
    - _assets/css/scss
    - _assets/images/shared
    - _assets/images/2018-01-08
    - _assets/images/2018-01-15
    - _assets/images/2018-01-22
    - _assets/images/2018-02-23
